#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#    Nov 19, 2019 07:49:35 PM EET  platform: Linux

import sys
from bot import bot
from threading import Thread
from jsonData import JSONDocument

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

botThr = None

def set_Tk_var():
    global api_key
    api_key = tk.StringVar()
    global admin
    admin = tk.StringVar()
    global DialogflowApi
    DialogflowApi = tk.StringVar()
    global sessionId
    sessionId = tk.StringVar()
    global language
    language = tk.StringVar()

    api_key.set(JSONDocument.getDataByKey('api_key'))
    admin.set(JSONDocument.getDataByKey('admin'))
    DialogflowApi.set(JSONDocument.getDataByKey('DialogflowApi'))
    sessionId.set(JSONDocument.getDataByKey('sessionId'))
    language.set(JSONDocument.getDataByKey('language'))

def onEndEnter(event):
    global api_key
    global admin
    global DialogflowApi
    global sessionId
    global language
    data = { 
        'api_key': api_key.get(), 
        'admin': admin.get(), 
        'DialogflowApi': DialogflowApi.get(), 
        'sessionId': sessionId.get(), 
        'language': language.get() 
    }
    JSONDocument.setAllData(data)

def botRun():
    bot.polling(timeout=0.1)

def onStartClick():
    global botThr
    botThr = Thread(target=botRun)
    botThr.start()

def onStopClick():
    bot.stop_polling()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import gui
    gui.vp_start_gui()




